zurg: v1
token: "rd token here"
download_tokens: 
strm_link_token:
host: "[::]"
port: 9999
base_url: "http://192.168.1.25:9999"
username: "admin"
password: "admin"
proxy: ""
concurrent_workers: 20
check_for_changes_every_secs: 10
repair_every_mins: 60
ignore_renames: false
retain_rd_torrent_name: false
retain_folder_name_extension: false
enable_repair: true
auto_delete_rar_torrents: true
cache_network_test_results: true
auto_analyze_new_torrents: true
emby_server_url: "http://192.168.1.25:8096"
emby_token: "emby token here"
get_downloads_limit: 1000
api_timeout_secs: 15
download_timeout_secs: 10
enable_download_mount: false
rate_limit_sleep_secs: 6
retries_until_failed: 2
network_buffer_size: 4194304 # 4MB
disable_stream_proxy: false
serve_strm_files: true
save_strm_files: true
verify_download_link: false
force_ipv6: false
# on_library_update: sh plex_update.sh "$@"
# for windows comment the line above and uncomment the line below:
# on_library_update: '& powershell -ExecutionPolicy Bypass -File .\plex_update.ps1 --% "$args"'
mount_path: ""
unrestrict_ip: "http://192.168.1.25:9999"

directories:
  anime:
    group_order: 10
    group: media
    filters:
      - regex: /\b[a-fA-F0-9]{8}\b/
      - any_file_inside_regex: /\b[a-fA-F0-9]{8}\b/

  shows:
    group_order: 20
    group: media
    filters:
      - has_episodes: true

  movies:
    group_order: 30
    group: media
    only_show_the_biggest_file: true
    filters:
      - regex: /.*/
